version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # เชื่อมไฟล์ในเครื่องกับใน Docker (แก้โค้ดปุ๊บ อัปเดตปั๊บ)
      - kaggle_cache:/root/.cache/kagglehub  # เก็บ Cache ไฟล์ Kaggle ไว้

volumes:
  kaggle_cache: